### ISSUE TITLE
20_pykrige_interface is broken

### ISSUE THREAD

**Issue by banesullivan** [GeoStat-Framework/GSTools#56]
I am currently working on a fork to make a [sphinx gallery](https://sphinx-gallery.github.io/stable/index.html) for GSTools and will make a PR soon.

At the moment, `examples/20_pykrige_interface.py` is failing with the following error:

```py
Traceback (most recent call last):
  File "/Users/bane/anaconda3/envs/dev/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/Users/bane/anaconda3/envs/dev/lib/python3.7/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/Users/bane/Software/external/GSTools/examples/20_pykrige_interface.py", line 30, in <module>
    OK1 = OrdinaryKriging(data[:, 0], data[:, 1], data[:, 2], cov_model)
  File "/Users/bane/anaconda3/envs/dev/lib/python3.7/site-packages/pykrige/ok.py", line 216, in __init__
    if self.variogram_model not in self.variogram_dict.keys() and \
TypeError: unhashable type: 'Gaussian'
```

**Comment by MuellerSeb** [comment]
This PR: https://github.com/bsmurphy/PyKrige/pull/125 is not merged since 7 months. With this it should work. I thought it would get working in the meantime...

**Comment by MuellerSeb** [comment]
This is because this PR: https://github.com/bsmurphy/PyKrige/pull/125 is not merged since half a year.
When I created this example I was hoping It'll be OK in the meantime...
